routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\SendController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\WelcomeController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class,'index']);

Route::get('/a2/{id}', function ($id,Request $request) {
    return $id;
    return $request->method();
    return view('welcome');
});

Route::get('/myroute', function () {
    return view('my');
});


//Route::prefix('products')->group(function(){
    Route::resource('products',ProductController::class);
//});

Route::middleware('auth')->group(function(){
    Route::post('/news', [NewsController::class,'store'])->name('news.store');
});


Route::get('/send/test', [SendController::class,'sendTest']);

Route::match(['get','post'],'/send/test2', [MailController::class,'send']);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['name','description','price'];
  //  protected $guarded = ['created_at','updated_at','id'];

    protected $attributes = ['price'=>100];
   
    protected $casts = ['price'=>'integer'];

    public function getRouteKeyName():string
    {
        return 'id';
    }
    
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       // $product = Product::where([['name','Новое 2'],['price','>',100]])->oldest()->limit(2)->get();
       $product = Product::distinct()->get(['name']);
        dd($product);

        $product = Product::firstWhere(function($query){
            $query->where('name','Новое 2')
                  ->where('price','>',100);
        });

    dd($product);


    



        $products = Product::orderBy('id')->paginate(4);
       // dd($products);
       return view('products.index',['products'=>$products]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

        /*
        $product = new Product();
        $product->name = 'Товар1';
        $product->description = 'Товар1 description';
        $product->price = 555;
        $product->save();
        */
        
       /*
        $product = new Product(['name'=>'Товар1','description'=>'Товар1 description','price'=>555]);
        $product->save();
       */
      /*
      $product = new Product();
      $products2 = $product->firstOrNew(['name'=>'Товар1','description'=>'Товар1 description','price'=>555]);
      $product->save();
      */

     /* $product = Product::withTrashed()->find([5,6,7,8]);*/

    //  dd($product);

     // $product->fill(['name'=>'Новое 2','description'=>'Товар2 description','price'=>755]);
    //$product->name = "Новое значение";
  //  $product->save();


   // $product->updateOrCreate(['name'=>'Новое 2'],['name'=>'Новое 2','description'=>'Товар2 description','price'=>777]);

//$product->delete();
   // $product->increment('price');

   // dd($product->wasChanged());

    //$product->save();

    //$product->restore();



  //  $product->forceDelete();

        /*
        $product2 = $product->replicate();
        $product2->fill(['name'=>'Новое 2','description'=>'Товар2 description','price'=>755]);
        $product2->save();
        */

   /* Product::insert(['name'=>'Новое 2','description'=>'Товар2 description','price'=>755],
    ['name'=>'Новое 2','description'=>'Товар2 description','price'=>755],
    ['name'=>'Новое 2','description'=>'Товар2 description','price'=>755],
    ['name'=>'Новое 2','description'=>'Товар2 description','price'=>755]);


    Product::where('price',755)->delete();

    Product::trancate();


*/
/*

$product = DB::connection('mysql')->table('products')->insert(['name'=>'Товар6','description'=>'Товар2 description','price'=>755]);

$product = Product::all(); 
  
*/
/* $product = Product::firstOrFail();

    $product = Product::firstOr(function(){
        return new Product(['name'=>'Новое 2','description'=>'Товар2 description','price'=>755]);
    });
*/
/*
            $product = Product::withCasts(['price'=>'int'])->when($request->name,
            function($query,$on){return $query->oldest();},
            function($query,$on){return $query->latest();}
            );

$products3 = $product->union($product1)->get();

        $request->validate([
            'name'=>'required|string',
            'description'=>'required|string',
           // 'price'=>'int'
        ]);
        Product::create($request->all());
        return redirect()->route('products.index');
    }
*/

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name'=>'required|string',
            'description'=>'required|string',
            'price'=>'numeric'
        ]);

        $product->update($request->all());
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="ol-lg-12">LARAVEL CRUD</div>
    <a href="/products/create"><button type="button" class="btn btn-warning">Добавить товар</button></a>
</div>
<div class="row">

<form method="POST" action="/products">
@csrf
<div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">NAME</label>
    <input name="name" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">DESCRIPTION</label>
    <input name="description" type="text" class="form-control" id="exampleInputPassword1">
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">PRICE</label>
    <input name="price" type="text" class="form-control" id="exampleInputPassword1">
  </div>
  
  <button type="submit" class="btn btn-primary">SEND</button>
</form>


</div>


@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="ol-lg-12">LARAVEL CRUD</div>
        <a href="/products/create"><button type="button" class="btn btn-warning">Добавить товар</button></a>
    </div>
    <div class="row">
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        <form method="POST" action="/products/{{ $product->id }}">
            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">NAME</label>
                <input name="name" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    value="{{ $product->name }}">
            </div>

            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">DESCRIPTION</label>
                <input name="description" type="text" class="form-control" id="exampleInputPassword1"
                    value="{{ $product->description }}">
            </div>

            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">PRICE</label>
                <input name="price" type="text" class="form-control" id="exampleInputPassword1"
                    value="{{ $product->price }}">
            </div>

            <button type="submit" class="btn btn-primary">SEND</button>
        </form>


    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="ol-lg-12">LARAVEL CRUD</div>
    <a href="/products/create"><button type="button" class="btn btn-warning">Добавить товар</button></a>
</div>
<div class="row">
<table class="table table-hover table-dark">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">created_at</th>
      <th scope="col">updated_at</th>
      <th scope="col">Редактирование</th>
      <th scope="col">Удалить</th>
    </tr>
  </thead>
  <tbody>
    @foreach($products as $product)
  <tr>
      <th scope="row">{{$product->id}}</th>
      <td><a href="/products/{{$product->id}}">{{$product->name}}</a></td>
      <td>{{$product->description}}</td>
      <td>{{$product->price}}</td>
      <td>{{$product->created_at}}</td>
      <td>{{$product->updated_at}}</td>
      <td><a href="{{route('products.edit',$product->id)}}">Редактировать</td>
      <td><form method="POST" action="{{route('products.destroy',$product->id)}}">@csrf   <input type="hidden" name="_method" value="DELETE"><button>Удалить</button></form></td>
    </tr>
    @endforeach
    
  </tbody>
</table>
{{$products->links()}}
</div>

<style>
    img, svg {

    width: 30px;
}
</style>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    {{$product->id}}
    {{$product->name}}

</div>


@endsection